services:
  user-service:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "4000:4000"
    volumes:
      - ./user-service:/app
      - user_service_node_modules:/app/node_modules
    env_file:
      - ./user-service/.env
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:5432/gotracks
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: gotracks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gotracks"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  user_service_node_modules:
